project:
  type: website

website:
  title: "Kyle Caron"
  description: "Welcome to my blog! I'm a self-taught data scientist interested in causal inference and bayesian methods. I mainly use this blog to formalize what I learn, but hopefully others find it helpful as well."
  google-analytics: "G-N3D0DYZCY4"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/kylejcaron
theme: default 
highlight-style: atom-one-light
format:
  html:
    css: theme.scss
    highlight-style: atom-one-light



